<?php

/*
 * Settings metadata file
 */
return array(
  'eventcalendar_calendar_title' => array(
    'group_name' => 'Event Calendar',
    'group' => 'eventcalendar',
    'name' => 'eventcalendar_calendar_title',
    'title' => 'Calendar Title',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Event calendar title.',
    'help_text' => '',
    'html_attributes' => array('class' => 'huge'),
  ),
  'eventcalendar_event_past' => array(
    'group_name' => 'Event Calendar',
    'group' => 'eventcalendar',
    'name' => 'eventcalendar_event_past',
    'title' => 'Show Past Events',
    'type' => 'Integer',
    'html_type' => 'checkbox',
    'quick_form_type' => 'Element',
    'default' => 1,
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Show past events as well as current/future.',
    'help_text' => '',
  ),
  'eventcalendar_event_end_date' => array(
    'group_name' => 'Event Calendar',
    'group' => 'eventcalendar',
    'name' => 'eventcalendar_event_end_date',
    'title' => 'Show End Date',
    'type' => 'Integer',
    'html_type' => 'checkbox',
    'quick_form_type' => 'Element',
    'default' => 1,
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Show the event with start and end dates on the calendar.',
    'help_text' => '',
  ),
  'eventcalendar_event_is_public' => array(
    'group_name' => 'Event Calendar',
    'group' => 'eventcalendar',
    'name' => 'eventcalendar_event_is_public',
    'title' => 'Show Public Events',
    'type' => 'Integer',
    'html_type' => 'checkbox',
    'quick_form_type' => 'Element',
    'default' => 1,
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Show only public events, or all events.',
    'help_text' => '',
  ),
  'eventcalendar_event_month' => array(
    'group_name' => 'Event Calendar',
    'group' => 'eventcalendar',
    'name' => 'eventcalendar_event_month',
    'title' => 'Events by Month',
    'type' => 'Integer',
    'html_type' => 'checkbox',
    'quick_form_type' => 'Element',
    'default' => 1,
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Show the month parameter on calendar.',
    'help_text' => '',
  ),
  'eventcalendar_event_from_month' => array(
    'group_name' => 'Event Calendar',
    'group' => 'eventcalendar',
    'name' => 'eventcalendar_event_from_month',
    'title' => 'Events from Month',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Show events from how many months from current month.',
    'help_text' => '',
    'html_attributes' => array('class' => 'four'),
  ),
  'eventcalendar_event_types' => array(
    'group_name' => 'Event Calendar',
    'group' => 'eventcalendar',
    'name' => 'eventcalendar_event_types',
    'title' => 'Events Types',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Choose which event types will be displayed, and how they will be colored.',
    'help_text' => '',
  ),
);
